### ISSUE TITLE
My Stream RS I Purchased for $30 with my card does not work. Please could you assist me in getting my coverage on.

### ISSUE THREAD

**Issue by MISTYB7** [STREAM-RS/STREAM-RS#1]
My STREAM RS is not working in which, I purchased on 07/12 for the application fee of $30. Could you please be so kind to assist me in launching the service. Thank you from the bottom of my heart. I look forward to hearing from you. Thank you.

**Comment by BrandonSmithJ** [comment]
Can you clarify what you paid for? This is free, open source software - there is no application fee or any other cost.

**Comment by MISTYB7** [comment]
Yes apparently you have not kept good records of transactions. I paid $30 from my bank account.  I paid for a service you did not honor. I need to know what steps will you take in providing me with stream rs?

**Comment by BrandonSmithJ** [comment]
There are no transactions to keep a record of, as we do not accept payment for this software. You have confused this repository for something else.

**Comment by MISTYB7** [comment]
Felicia Erwin setup the stream RS service. I paid for the information that were given to her. The account is in Felicia Erwin name. My account was debited July 17th for $30 for 3months service.

**Comment by MISTYB7** [comment]
My name is Jerri Williams the payor of the stream RS account.
